"""add column date_completed

Revision ID: 54f85f5c6283
Revises: 209b71621905
Create Date: 2025-01-05 01:24:36.588298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f85f5c6283'
down_revision: Union[str, None] = '209b71621905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date_completed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'date_completed')
    # ### end Alembic commands ###
