"""feat: subtasks

Revision ID: 5677949fe6ef
Revises: 41ccd2241537
Create Date: 2025-01-03 15:00:27.059072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5677949fe6ef'
down_revision: Union[str, None] = '41ccd2241537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_parent_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('type', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'tasks', 'tasks', ['task_parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'task_parent_id')
    # ### end Alembic commands ###
