"""add status column for otp table 2

Revision ID: ab4407bb30a5
Revises: 9dabd1cca434
Create Date: 2025-01-07 00:56:48.454981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4407bb30a5'
down_revision: Union[str, None] = '9dabd1cca434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'status')
    # ### end Alembic commands ###
